# Generated by Django 3.2.6 on 2022-10-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('is_stop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, verbose_name='باركود')),
                ('name_lo', models.CharField(max_length=50, unique=True, verbose_name='اسم الصنف المحلي')),
                ('name_fk', models.CharField(default='', max_length=50, verbose_name='اسم الصنف الاجنبي')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.category')),
                ('items_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.items_type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.unit')),
            ],
        ),
        migrations.CreateModel(
            name='story_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='الكمية')),
                ('date_in', models.IntegerField(verbose_name='تاريخ الاضافة')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.items')),
                ('stor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.store')),
            ],
        ),
    ]
