# Generated by Django 3.2.6 on 2023-08-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('is_stop', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=50, verbose_name='باركود')),
                ('name_lo', models.CharField(max_length=50, unique=True, verbose_name='اسم الصنف المحلي')),
                ('name_fk', models.CharField(default='', max_length=50, verbose_name='اسم الصنف الاجنبي')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_createdby', to=settings.AUTH_USER_MODEL)),
                ('items_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.items_type')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='story_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(verbose_name='الكمية')),
                ('exp_date', models.DateField(verbose_name='تاريخ الإنتهاء ')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_items_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_items_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('stor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
