# Generated by Django 3.2.6 on 2023-08-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configrate', '0001_initial'),
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_items',
            name='stor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configrate.store'),
        ),
    ]
