# Generated by Django 3.2.6 on 2023-12-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20230818_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_items',
            name='exp_date',
        ),
    ]
