# Generated by Django 3.2.6 on 2024-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_remove_story_items_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item', verbose_name='صورة المنتج'),
        ),
    ]
