# Generated by Django 3.2.6 on 2024-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='purch_price',
            field=models.CharField(default=0, max_length=100, verbose_name='Purchased Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='salse_price',
            field=models.CharField(default=0, max_length=100, verbose_name='Salse Price'),
            preserve_default=False,
        ),
    ]
