# Generated by Django 3.2.6 on 2023-08-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configrate', '0001_initial'),
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoicelocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date')),
                ('is_stage', models.BooleanField(default=False, verbose_name='is stage')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='is suspended')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='tax')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('check_amount', models.FloatField(blank=True, null=True, verbose_name='Check Amount')),
                ('supplier_bill_number', models.IntegerField(blank=True, null=True, verbose_name='Supplier Bill Number')),
                ('supplier_bill_date', models.DateField(blank=True, null=True, verbose_name='Supplier Bill Date')),
                ('stop', models.BooleanField(default=False, verbose_name='Stop')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Total Amount For Invoicelocal')),
                ('statement', models.CharField(max_length=100, verbose_name='Statement')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='discount rate %')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoicelocal_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoicelocal_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Invoice local',
                'db_table': 'purchase_invoicelocal',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الجوال')),
                ('is_stop', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoicelocalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(verbose_name='qty')),
                ('free_qty', models.PositiveIntegerField(default=0, verbose_name='free qty')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expire date')),
                ('statement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statement')),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Discount')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='discount %')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Selling price')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoicelocaldetails_createdby', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='input.items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseinvoicelocaldetails_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoicelocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoicelocal')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configrate.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configrate.unit')),
            ],
            options={
                'verbose_name': 'purchase invoicelocal details',
                'db_table': 'purchase_invoicelocal_details',
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoicelocal',
            name='supplir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='supplier'),
        ),
    ]
