# Generated by Django 3.2.6 on 2022-10-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configrate', '0001_initial'),
        ('input', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='السعر')),
                ('qty', models.IntegerField(null=True, verbose_name='الكمية')),
                ('date_end', models.DateField(verbose_name='تاريخ الإنتهاء')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.items', verbose_name='الصنف')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(verbose_name='الملاحظة')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='الإجمالي')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.store', verbose_name='المخز')),
            ],
        ),
    ]
