# Generated by Django 3.2.6 on 2022-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchases_purchasesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesdetails',
            name='Purchases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchases'),
            preserve_default=False,
        ),
    ]
