# Generated by Django 3.2.6 on 2022-11-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasesdetails_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasesdetails',
            old_name='Purchases',
            new_name='purchases',
        ),
    ]
