# Generated by Django 3.2.6 on 2023-07-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configrate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0001_initial'),
        ('purchases', '0004_rename_purchases_purchasesdetails_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basemodel_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basemodel_modifiedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasesdetails',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchasesdetails',
            name='purchases',
        ),
        migrations.CreateModel(
            name='DiscountCodingPurchases',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.basemodel')),
                ('unit', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Unit')),
                ('ratio_amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Ratio Amount %')),
                ('the_value', models.IntegerField(blank=True, default=None, null=True, verbose_name='The Value')),
                ('dis', models.FloatField(max_length=150, verbose_name='Discount')),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='input.items', verbose_name='Item ID')),
            ],
            options={
                'verbose_name': 'Discount Coding Purchases',
            },
            bases=('purchases.basemodel',),
        ),
        migrations.CreateModel(
            name='PurchaseInvoicelocal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.basemodel')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date')),
                ('is_stage', models.BooleanField(default=False, verbose_name='is stage')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='is suspended')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='tax')),
                ('exchange_rate', models.FloatField(verbose_name='Exchange Rate')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('payment_method', models.CharField(choices=[('1', 'Cash'), ('2', 'Check'), ('3', 'debt'), ('4', 'Cash/Check')], max_length=15, verbose_name='Payment Method')),
                ('check_amount', models.FloatField(blank=True, null=True, verbose_name='Check Amount')),
                ('supplier_bill_number', models.IntegerField(blank=True, null=True, verbose_name='Supplier Bill Number')),
                ('supplier_bill_date', models.DateField(blank=True, null=True, verbose_name='Supplier Bill Date')),
                ('stop', models.BooleanField(default=False, verbose_name='Stop')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Total Amount For Invoicelocal')),
                ('statement', models.CharField(max_length=100, verbose_name='Statement')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='discount rate %')),
                ('supplir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Purchase Invoice local',
                'db_table': 'purchase_invoicelocal',
            },
            bases=('purchases.basemodel',),
        ),
        migrations.CreateModel(
            name='PurchaseInvoicelocalDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchases.basemodel')),
                ('qty', models.PositiveIntegerField(verbose_name='qty')),
                ('free_qty', models.PositiveIntegerField(default=0, verbose_name='free qty')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='expire date')),
                ('statement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statement')),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Discount')),
                ('discount_rate', models.FloatField(blank=True, null=True, verbose_name='discount %')),
                ('selling_price', models.FloatField(blank=True, null=True, verbose_name='Selling price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='input.items')),
                ('purchase_invoicelocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoicelocal')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configrate.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configrate.unit')),
            ],
            options={
                'verbose_name': 'purchase invoicelocal details',
                'db_table': 'purchase_invoicelocal_details',
            },
            bases=('purchases.basemodel',),
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='PurchasesDetails',
        ),
    ]
