# Generated by Django 3.2.6 on 2023-07-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20230706_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoicelocal',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoicelocal',
            name='payment_method',
        ),
    ]
