# Generated by Django 3.2.6 on 2023-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('is_stop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('codeUnit', models.CharField(max_length=50, verbose_name='رمز الوحدة')),
            ],
        ),
    ]
