# Generated by Django 3.2.6 on 2022-08-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, verbose_name='باركود')),
            ],
        ),
        migrations.CreateModel(
            name='Items_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('is_stop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='story_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='الكمية')),
                ('date_in', models.IntegerField(verbose_name='تاريخ الاضافة')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.items')),
                ('stor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.store')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lo', models.CharField(max_length=50, verbose_name='الاسم المحلي')),
                ('name_fk', models.CharField(max_length=50, verbose_name='الاسم الاجنبي')),
                ('codeUnit', models.CharField(max_length=50, verbose_name='رمز الوحدة')),
            ],
        ),
        migrations.DeleteModel(
            name='UserR',
        ),
        migrations.AddField(
            model_name='items',
            name='items_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.items_type'),
        ),
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configrate.unit'),
        ),
    ]
