# Generated by Django 3.2.6 on 2024-07-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='Device',
            new_name='device',
        ),
    ]
