# Generated by Django 3.2.6 on 2024-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_device_session_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
