# Generated by Django 3.2.6 on 2024-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('opne', 'open')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
