# Generated by Django 3.2.6 on 2024-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('opne', 'open'), ('closed', 'closed')], default='opne', max_length=10),
        ),
    ]
