# Generated by Django 3.2.6 on 2024-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(blank=True, choices=[('closed', 'closed'), ('open', 'open')], default='open', max_length=10, null=True),
        ),
    ]
