# Generated by Django 3.2.6 on 2023-12-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesinvoicelocaldetails_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoicelocaldetails',
            name='expire_date',
        ),
    ]
